### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by o-kasian** [dmarkrollins/camelot#1]
## What

As of now repository does not have any LICENSE file, and it is not clear if other people can actually use this product and what are the conditions.

## Why

* As a user I want to understand use conditions
* As a contributor I want to understand if I can reuse the code and propose new features

## How

Add LICENSE.txt/LICENSE.md document to repository root

**Comment by dmarkrollins** [comment]
Ha, fantastic idea! Hopefully can get a license set up this week.

**Comment by dmarkrollins** [comment]
MIT  license added
